version: '3.8'

x-cfssl: &cfssl
  image: ${REPOSITORY:-takumi/cfssl}:latest
  command: cfssl serve
  healthcheck:
    test:         ["CMD", "wget", "--spider", "-q", "http://localhost:8888/api/v1/cfssl/health"]
    interval:     1s
    timeout:      3s
    retries:      3
    start_period: 60s
  cap_add:
    - FOWNER
    - CHOWN
    - SETUID
    - SETGID
  cap_drop:
    - ALL
  networks:
    - cfssl
  environment:
    TZ: Asia/Tokyo
  restart: unless-stopped

services:
  #
  # CFSSL
  #
  cfssl:
    <<: *cfssl
    hostname: cfssl
    container_name: cfssl

networks:
  cfssl:
    name: cfssl
